### ISSUE TITLE
Issue with "extract": encoding `` not recognised

### ISSUE THREAD

**Issue by shymu** [xeals/signal-back#10]
I'm trying to extract a backup made on Signal 4.18.3 on a Samsung Galaxy Alpha.

The backup completed (seemingly) successfully on the phone and the backup file was then transferred to a MacBook Pro using Google's "Android File Transfer" app.

Running signal-back with the "analyse" option on this file seems to work just file, which leads me to believe the backup file is good, when I try to run an extract I get this error:

```
./signal-back_darwin_amd64 extract -p [pass] signal-[date].backup 
error: failed to extract attachment: encoding `` not recognised. create a PR or issue if you think it should be
```

I can't figure out if this is an error related to the backup file or signal-back, or how to further diagnose this.

**Comment by xeals** [comment]
`extract` uses MIME types to determine output file extensions. I'm not sure why it doesn't have a recognised MIME type, but I've pushed a fix that will just give debug output instead. Are you able to build the program from source to have another try?

**Comment by shymu** [comment]
I was able to build from source, but it doesn't give me much more info, just a timestamp:

```
$ ./signal-back extract -p [pass]  signal-[date].backup 
2018/04/30 07:53:30 encoding `` not recognised. create a PR or issue if you think it should be
```

**Comment by xeals** [comment]
I made the wrong change. In `cmd/extract.go`, can you change the two instances of `log.Fatalf` at lines 224 and 225 to `log.Printf` instead?

**Comment by shymu** [comment]
Ok, now I get 504 lines of this, before it finally ends (here's just a snippet from the end):

```
2018/04/30 08:06:09 encoding `` not recognised. create a PR or issue if you think it should be
2018/04/30 08:06:09 if you can provide details on the file `1495031440126` as well, it would be appreciated
2018/04/30 08:06:09 encoding `` not recognised. create a PR or issue if you think it should be
2018/04/30 08:06:09 if you can provide details on the file `1495036527311` as well, it would be appreciated
2018/04/30 08:06:09 encoding `` not recognised. create a PR or issue if you think it should be
2018/04/30 08:06:09 if you can provide details on the file `1495064583717` as well, it would be appreciated
2018/04/30 08:06:09 encoding `` not recognised. create a PR or issue if you think it should be
2018/04/30 08:06:09 if you can provide details on the file `1495165660156` as well, it would be appreciated
error: failed to extract attachment: failed to open output file: open 1495165660156.: too many open files
```

**Comment by shymu** [comment]
How do I figure out what the file is supposed to be? Without an extension I'm not sure where to start...

**Comment by xeals** [comment]
MacOS (iirc) determines file type by encoding rather by extension (like Windows does), so you could just try opening them from finder. If that doesn't work, try a text editor and see if they're at least plaintext. If that also doesn't work, I might need to check that I'm extracting from the right place in the backup.

Another alternative might be to change around line 72 to be the following:

```go
if len(ps) == 25 {
  aEncs[*ps[19].IntegerParameter] = *ps[3].StringParamter
  if *ps[19].IntegerParameter == 1495165660156 {
    fmt.Printf("%#v", ps)
  }
}
```

Note that that might contain sensitive information, so censor at will if you need to.

**Comment by neurolit** [comment]
Hi!

Same warnings for me on MacOS. I compiled your updated code and extracted every file of my backup. Attachment files are extracted without any extension. They are JPG, PNG and MPEG files.

**Comment by xeals** [comment]
If you can build and run the code in the `devel` branch, that might give me some insight.

**Comment by shymu** [comment]
Hey sorry, there was some degree of user error on my part, these files actually were extracting to my $GOPATH/bin/ (since that's where I was running the command apparently) and not where my backup was located.

Similar to @neurolit's findings, the files seem to be a mix of JPG, PNG and MPEG, all without extensions.

Anyway, I pulled the latest master, built, set `ulimit -n 1024`, and tried again.

This time it "completed" but every file still dumped something like this to the console:

```
2018/04/30 20:57:01 encoding `` not recognised. create a PR or issue if you think it should be
2018/04/30 20:57:01 if you can provide details on the file `1522622403410` as well, it would be appreciated
```

The referenced file, `1522622403410` is able to be previewed in finder (though it seems to lack any MIME data) and if I add a .jpg to the filename I can open it just fine.

**Comment by shymu** [comment]
There are some files that finder doesn't seem to know what to do with and I can't figure out what they are either. For example:

```
$ file -I 1522811988909 
1522811988909: application/octet-stream; charset=binary
```

**Comment by xeals** [comment]
Can you run the same on the `devel` branch? It should give a little more debugging output.

**Comment by shymu** [comment]
Unfortunately I've only been using git since I filed this bug, so forgive me for having such a basic issue, but I'm not sure how to pull the `devel` branch? So far I've tried:

```
$ git checkout devel
error: pathspec 'devel' did not match any file(s) known to git.
```

to no avail :(

**Comment by xeals** [comment]
All good.

```
$ git pull origin devel
$ git checkout devel
```

**Comment by shymu** [comment]
Nothing new

```
2018/04/30 21:24:34 encoding `` not recognised. create a PR or issue if you think it should be
2018/04/30 21:24:34 if you can provide details on the file `1522811988909` as well, it would be appreciated
```

**Comment by xeals** [comment]
Oh, that's more interesting.

I was under the impression that every attachment (stored as a binary blob in the backup) came with a matching `parts` SQL query containing metadata. If it's not running the part I've been changing, there's no metadata entry (or it's out of order). The next change will just spit everything it finds. If you can put the entire thing into a gist/pastebin/etc. that'd be great. It shouldn't contain anything sensitive.

**Comment by neurolit** [comment]
I tried with the `devel` branch:

With `extract`:
```
found attachment binary 1524953561841

2018/05/02 14:41:28 encoding `` not recognised. create a PR or issue if you think it should be
2018/05/02 14:41:28 if you can provide details on the file `1524953561841` as well, it would be appreciated
```

And with `analyze`:
```
map[insert_into_part:689 attachment:688 insert_into_identities:4 pref:2 create_index:19 drop_index:19 insert_into_thread:9 drop_table:13 create_table:13 insert_into_sms:32039 insert_into_mms:691 insert_into_recipient_preferences:538 avatar:1 version:1]
```

**Comment by xeals** [comment]
Is that the entire output of `extract`?

**Comment by neurolit** [comment]
I have 688 attachments (approx. 2000 lines of logs). For each attachment, I've got these 4 lines, yes.

**Comment by xeals** [comment]
If it's not giving any lines starting with `found attachment metadata`, then I'm at a loss.

I've pushed a change that tries to guess encoding based on the file contents. You'll need to `dep ensure` before trying to run again.

**Comment by neurolit** [comment]
It works! 

Logs (for one attachment):
```
2018/05/02 15:24:28 found attachment binary 1524953561841

2018/05/02 15:24:28 file `1524953561841` has no associated SQL entry; going to have to guess at its encoding
```

Files have now the right extension, except for three of them (*.unknown files):
```
$ file *.unknown
1498568946944.unknown: MPEG ADTS, AAC, v4 LC, 44.1 kHz, monaural
1519327446092.unknown: MPEG ADTS, AAC, v4 LC, 44.1 kHz, monaural
1522171621751.unknown: ISO Media
```

**Comment by xeals** [comment]
Good. Thanks for your help with this. I don't think there's much I can do about those files myself, but it might be worth dropping an issue over at [the upstream repo](https://github.com/h2non/filetype) with the file types and initial X bytes if you're willing.
