### ISSUE TITLE
No Errors, Empty Output File

### ISSUE THREAD

**Issue by soehlert** [xeals/signal-back#20]
- Signal-back: v0.1.6-alpha.1
- Binary: darwin_amd64
- OS: MacOS High Sierra 10.13.4
- Backup file size: 
    `382M Jun 26 01:14 signal-2018-06-26-00-56-36.backup`
- Command run: 
     `./signal-back_darwin_amd64 format -f XML signal-2018-06-26-00-56-36.backup > backup.xml`
- Decrypted file size: 
     `0B Jun 26 01:36 backup.xml`

I've tried using the CSV format as well and the same thing happened. I run the command, then enter my passcode. It runs without error and takes a few seconds, then just shows the cursor waiting at the next prompt.

**Comment by xeals** [comment]
Can you run it again with the `-v` flag and see what it says?

**Comment by soehlert** [comment]
I get a whole bunch of `2018/06/26 02:05:57 MMS export not yet supported` notifications (which I expect). 

Then I get `2018/06/26 02:05:59 error reading: initialising frame: unexpected EOF` which seems like the actual issue. That is when the process dies and I get dumped to the next prompt.

**Comment by xeals** [comment]
Does this issue occur on the stable release as well?

**Comment by soehlert** [comment]
Using the stable release fixed it all. I was able to export XML and import into the SMS client I wanted to use. Thanks so much! Not sure if there's any other useful info I can give you to help find the bug in the alpha version, but just let me know if there is.

**Comment by goatandsheep** [comment]
which is the stable release?

**Comment by Myzel394** [comment]
> which is the stable release?

Did you find it out @goatandsheep ?

**EDIT**

Tried [signal-backup-decode](https://github.com/pajowu/signal-backup-decode), which worked like a charm

**Comment by goatandsheep** [comment]
No i never did and gave up 😢
