### ISSUE TITLE
Generated XML file doesn't work with SMS Backup & Restore

### ISSUE THREAD

**Issue by kdmcguire** [xeals/signal-back#21]
Decoding and generating the file seems to work, and I when viewing the file in Sublime Text the format seems okay.

When trying to restore with SMS Backup & Restore, though, the file is not shown to you as an option to restore from.

When browsing backup files within the app the file is given a label of "Invalid File - 22.8MB".

Any ideas on what might be causing this issue? Is it likely to be a formatting issue, or an incompatibility with some of my messages?

**Comment by kdmcguire** [comment]
Seems to have been down to filesize.

I went through the generated file, adding line-breaks and indents so that it was formatted correctly and easier to read.

Then I split that one file into several of 5000 <sms> messages (1 per line) each, updating the SMS count to 5000, and giving them the right opening and closing lines.

SMS Backup & Restore then seemed to accept the new files and let me use them to restore.

**Comment by xeals** [comment]
That's interesting. I haven't heard of it having a file size limit before. Formatting should be fine regardless, since XML isn't picky about indentation. I'm assuming this was on `0.1.5`?

**Comment by kdmcguire** [comment]
I think so! I'm away from my machine now but I'll double-check later.

It might not be file-size: after all of my 5000-message files finished importing, I made a fresh backup with SMS Backup & Restore. It contains some duplicates, so it's even larger than the original file this tool generated... but SMS B & R is offering treats it like a valid file and offers to use it.

**Comment by xeals** [comment]
Unless this crops up again, I'm going to say that this was fixed by 679fc38fd906b232ac712bac9d1cb1d7fdc88030 and adding newlines. Closing.

**Comment by oathbound** [comment]
Also having this issue.  
Pixel 1, Android P as delivered (as soon as it installed my phone lost wifi and can only do lte, so updates are off).
