### ISSUE TITLE
Wrong encoding

### ISSUE THREAD

**Issue by kostas888** [xeals/signal-back#28]
I am from russia.
So, when I encrypte backup file, english text is ok, but all cyrylic text is wrong in hieroglyphs.
And the encrypted file is in UCS-2 Little Endian, not in UTF-8.
What's happening?

Windows 10 64bit.

**Comment by kostas888** [comment]
?

**Comment by xeals** [comment]
I'm unable to reproduce this on Linux. I suspect this may be an issue in Windows. I'll try and make time to spin up a VM to confirm that idea.

**Comment by xeals** [comment]
Actually, does the problem persist if you use the `-o` flag instead of piping output from the program? There's a couple of articles around that suggest the Windows terminal doesn't like UTF-8, so it may be being mangled in the pipeline.

**Comment by antonio-gil** [comment]
Hi.

I was having the same issue, as my language is Spanish and I was having trouble getting the accentuated vowels (á, é, í, ó, ú) correctly. But after toying with the workaround mentioned here, and in #29 , I've managed to get those letters correctly, and the emojis too!

I'm using powershell as me default CLI, and I managed to get the correct result with this commands:

`.\signal-back_windows_amd64.exe format -f XML .\signa-.backup | out-file "test.xml" -encoding oem`

Emojis:

![image](https://user-images.githubusercontent.com/9835489/44320396-5ae35200-a431-11e8-9c51-dae0abefae91.png)

Accentuated vowels:

![image](https://user-images.githubusercontent.com/9835489/44320407-6fbfe580-a431-11e8-920b-91ca9f7e3763.png)

Perhaps it isn't an elegant solution, but as long as it works  ¯\_(ツ)_/¯ ...

**Comment by kostas888** [comment]
@antonio-gil Thank you very much! Now it's ok!

**Comment by antonio-gil** [comment]
Glad to hear that, @kostas888 😃

**Comment by xeals** [comment]
The `out-file` Powershell cmdlet correctly handles UTF I would suspect. I'll mark this as closed unless the issue crops up again, and I'll add it to the wiki.
