### ISSUE TITLE
[feature request] disable password echo

### ISSUE THREAD

**Issue by kaefert** [xeals/signal-back#41]
It would be nice if you could disable password echo.

I just downloaded your prebuild binary for version v0.1.6 "signal-back_linux_amd64" and tried analyse & check commands, and saw that it echoed my backup password back to me.

Industry standard seems to me to either disable echo for password completely or echo stars instead to show how many characters have been entered.

- Operating system: Linux Mint 19 Kernel 4.15.0-39
- Build version (`signal-back --version`): signal-back v0.1.6-dirty, proto commit: d6610f0

**Comment by xeals** [comment]
Resolved. I can look into echoing stars at a later date, but it's a bit more tricky than just disabling echo. I may provide a flag later on to enable the echo again. My initial reasoning was that the backup code wasn't particularly needing to be secure, as you needed to have both the file and the password for it to be useful.
