### ISSUE TITLE
Failed to format

### ISSUE THREAD

**Issue by JacobMH1** [xeals/signal-back#50]
I have no clue what I've done wrong, I'm very out of my element with all this. I have no coding experience so I'm just throwing darts. I tried to put my password in a txt file and do the "-P password.txt" but it had no difference.

error: failed to open backup file: unable to open backup file: FindFirstFile signal-XXX.backup: The system cannot find the file specified.
<img width="532" alt="capture" src="https://user-images.githubusercontent.com/48344584/54010745-421c5e80-412d-11e9-95b6-f68602fc2b0a.PNG">

<img width="663" alt="capture2" src="https://user-images.githubusercontent.com/48344584/54010815-8871bd80-412d-11e9-9162-11fb8cb8c531.PNG">

Windows 10 64-bit
Build version 4.17.5

**Comment by GuardianMajor** [comment]
Because you are using the wrong filename.
signal-`xxx`.backup is a placeholder, you need to use YOUR filename.
Try that and it will find it.
In your case: `signal-2019-03-07-22-32-23.backup` I presume from the image.

**Comment by JacobMH1** [comment]
Oh, well then. Issue closed lol.

**Comment by GuardianMajor** [comment]
Glad you got it resolved.
