### ISSUE TITLE
Panic: Undefined SMS type: 24

### ISSUE THREAD

**Issue by Bluther** [xeals/signal-back#6]
As the title says, getting a panic on SMS type 24 when trying to format.

According to my novice interpretation of [Signal's code repo](https://github.com/signalapp/Signal-Android/blob/f17c144a60df158a117845c7f1371d9c34e81ec1/src/org/thoughtcrime/securesms/database/MmsSmsColumns.java), it looks like it's choking on the `SENT_FAILED` type:

```
protected static final long BASE_INBOX_TYPE                    = 20;
protected static final long BASE_OUTBOX_TYPE                   = 21;
protected static final long BASE_SENDING_TYPE                  = 22;
protected static final long BASE_SENT_TYPE                     = 23;
protected static final long BASE_SENT_FAILED_TYPE              = 24;
protected static final long BASE_PENDING_SECURE_SMS_FALLBACK   = 25;
```

I'd provide more info about the specific message, if you can let me know how. I'm unsure how to dive into the backup itself.

**Comment by Bluther** [comment]
I'd provide more info about the specific message, if you can let me know how. I'm unsure how to dive into the backup itself.

**Comment by xeals** [comment]
Thanks for reporting. Looks like I forgot to hook up Signal's insecure protocols.
