### ISSUE TITLE
panic: undefined SMS type: 0x57

### ISSUE THREAD

**Issue by tssva** [xeals/signal-back#7]
Trying to output an XML format generates a 'panic: undefined SMS type: 0x57' error. Looking through the cvs output of the backup I found the message. It is the result of selecting Invite in the conversation menu. 

First there is a message with the body "Let's switch to Signal: https://sgnl.link/1KpeYmF" and a type of 23 (sent). Immediately following is the message with type 87 (0x57) with the same body.

**Comment by xeals** [comment]
Are you able to share the relevant lines in XML or CSV (either here or by email)? I don't have a second device to reproduce this, unfortunately.

**Comment by tssva** [comment]
Here are the two relevant lines with the phone number masked out.

```
1,1,+1XXXXXXXXXX,1,1523214053842,1523214053840,1,-1,87,0,Let's switch to Signal: https://sgnl.link/1KpeYmF,-1,0,0,0,0
2,1,+1XXXXXXXXXX,1,1523214054594,1523214054594,1,-1,23,0,Let's switch to Signal: https://sgnl.link/1KpeYmF,-1,0,0,0,0
```

**Comment by xeals** [comment]
The issue came from the the fact that Signal has a different protocol number for a forced SMS (because other it might try to use Signal's messaging to send an invite, which wouldn't work). Latest release should fix that.
