### ISSUE TITLE
CSV records have a variable number of fields

### ISSUE THREAD

**Issue by tssva** [xeals/signal-back#8]
CSV records have a variable number of fields. I assume the missing fields for any given record are suppose to be empty fields.

For example records with type 20 and 23 have a differing number of fields. And neither of them have the 22 fields I would expect based upon the header.

```
365,1,+1XXXXXXXXXX,1,97,1522112554906,1522112554906,0,1,-1,20,0,0,It's ok. Not too bad ,+12819659999,-1,0,0,0,0
366,1,+1XXXXXXXXXX,1,1522111363707,1522111363707,1,-1,23,0,How is the job going?,-1,0,0,0,0
```

**Comment by xeals** [comment]
I'm pretty sure I've identified why this is happening and was an oversight on my part. The fix should be coming within the next few hours.

**Comment by xeals** [comment]
I've pushed a new release to hopefully fix this. If it doesn't fix the issue, feel free to re-open and I'll have another look.
